# Generated by Django 5.1.6 on 2025-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
