# Generated by Django 5.1.6 on 2025-03-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0003_alter_image_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='bits.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='bits.person')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('person', 'item')},
            },
        ),
    ]
