# Generated by Django 5.1.6 on 2025-03-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0004_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
