# Generated by Django 5.1.6 on 2025-03-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0004_category_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product_name',
        ),
    ]
