# Generated by Django 5.1.6 on 2025-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0005_delete_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('name', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('campus', models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others')], default='GOA', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='image',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
