# Generated by Django 5.1.6 on 2025-03-20 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0005_rename_name_item_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_name',
            new_name='name',
        ),
    ]
