# Generated by Django 5.1.6 on 2025-03-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0006_rename_product_name_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_column='name', max_length=100),
        ),
    ]
