# Generated by Django 5.1.6 on 2025-03-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0007_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='product_name',
        ),
    ]
