# Generated by Django 5.1.6 on 2025-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0007_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
