# Generated by Django 5.1.6 on 2025-03-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0008_alter_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hostel',
            field=models.ForeignKey(default='CH1', on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='bits.hostel'),
        ),
    ]
