# Generated by Django 5.1.6 on 2025-03-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0008_rename_name_item_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_name',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
