# Generated by Django 5.1.6 on 2025-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0010_alter_person_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='campus',
            field=models.CharField(choices=[('GOA', 'Goa'), ('HYD', 'Hyderabad'), ('PIL', 'Pilani'), ('OTH', 'Others')], max_length=4),
        ),
    ]
