# Generated by Django 5.1.6 on 2025-03-15 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits', '0011_alter_person_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='bits.hostel'),
        ),
    ]
